#pragma once

// ─── sim_lidar.h ─────────────────────────────────────────────────────────────
// SimLidar — a drop-in replacement for LD06 / RPLidarA1 that feeds the entire
// pipeline with frames generated by SimWorld instead of a real serial port.
//
// Design contract
// ───────────────
// SimLidar inherits LidarBase EXACTLY the same way LD06 and RPLidarA1 do.
// From the perspective of every other module (perception, prediction, audio,
// agent, main.cpp), it is completely indistinguishable from a real sensor:
//
//   auto lidar = sensors::make_lidar(sensors::LidarModel::Sim, "sim://sidewalk");
//   lidar->open();
//   lidar->start();
//   // ... poll lidar->get_latest_frame() at 10 Hz — exactly as with real hw
//   lidar->stop();
//   lidar->close();
//
// The "port" string passed to the constructor is used as a scene selector:
//   "sim://sidewalk"        — default outdoor suburban sidewalk
//   "sim://crossing"        — pedestrian crossing path ahead
//   "sim://hallway"         — narrow corridor, walls both sides
//   "sim://parking_lot"     — parked cars, slow-moving vehicle
//   "sim://cyclist_overtake"— cyclist overtaking from behind-left
//   "sim://crowd"           — busy street, multiple pedestrians
//   Any other string or "" uses the default sidewalk scene.
//
// Thread model
// ────────────
// Identical to the real drivers:
//   - open() / start() / stop() / close() on the caller thread
//   - A background thread (sim_thread_) generates frames at SIM_HZ (10 Hz)
//     using SimWorld::step() + SimWorld::cast_rays()
//   - get_latest_frame() is protected by frame_mutex_ — same as LD06
//   - set_frame_callback() works identically
//
// Isolation guarantee
// ───────────────────
// This file includes ONLY:
//   sensors/lidar_base.h    — for LidarBase, ScanFrame, ScanPoint
//   sim/sim_world.h          — for SimWorld, NoisedRay
//   Standard library headers
//
// It does NOT include anything from perception/, prediction/, audio/, or agent/.
// The simulation is a sensor — it lives at the bottom of the dependency stack.
//
// Noise fidelity
// ──────────────
// SimWorld applies the full LD06 noise model before handing rays to SimLidar.
// SimLidar's only job is to pack NoisedRay results into ScanFrames with the
// correct metadata (frame_id, timestamp, sensor_rpm) and deliver them to the
// pipeline at the correct rate.
//
// Timing
// ──────
// The sim thread sleeps between frames to match the real LD06's 10 Hz output.
// SIM_HZ is configurable at construction — set it higher for stress testing
// (the pipeline will process frames as fast as they arrive) or lower to
// simulate a degraded sensor spinning slowly.

#include "sensors/lidar_base.h"
#include "sim/sim_world.h"

#include <thread>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <chrono>
#include <string>
#include <memory>
#include <functional>
#include <cstdint>
#include <cmath>

namespace sim {

// ─── SceneId ──────────────────────────────────────────────────────────────────
// Parsed from the "port" string passed to SimLidar("sim://...").

enum class SceneId {
    Sidewalk,         // default: suburban sidewalk, mixed pedestrians
    Crossing,         // pedestrian crossing path at an intersection
    Hallway,          // narrow indoor-style corridor (walls both sides)
    ParkingLot,       // parked cars, slow-moving vehicle
    CyclistOvertake,  // cyclist overtaking from behind-left at speed
    Crowd,            // busy street: 5+ pedestrians, mixed directions
};

// Parse the scene name from a "sim://scene_name" port string.
// Falls back to Sidewalk for any unrecognised input.
inline SceneId parse_scene_id(const std::string& port) {
    // Strip leading "sim://"
    std::string name = port;
    const std::string prefix = "sim://";
    if (name.rfind(prefix, 0) == 0) {
        name = name.substr(prefix.size());
    }
    if (name == "crossing")         return SceneId::Crossing;
    if (name == "hallway")          return SceneId::Hallway;
    if (name == "parking_lot")      return SceneId::ParkingLot;
    if (name == "cyclist_overtake") return SceneId::CyclistOvertake;
    if (name == "crowd")            return SceneId::Crowd;
    return SceneId::Sidewalk;
}

// ─── SimConfig ────────────────────────────────────────────────────────────────
// Runtime-tunable parameters for the simulated sensor.
// All have sensible defaults matching the real LD06.

struct SimConfig {
    // Scan rate in Hz. Real LD06 = 10 Hz. Set higher for stress testing.
    float  scan_hz          = 10.0f;

    // Number of rays per sweep. Real LD06 ≈ 460 at 10 Hz.
    int    rays_per_sweep   = 460;

    // Random seed for the noise model. 0 = time-based (non-deterministic).
    // Set to any non-zero value for fully reproducible runs.
    uint32_t rng_seed       = 0;

    // If true, the simulated user walks forward at world.user_speed_mm_s.
    // If false, the user stands still (useful for static scene tests).
    bool   user_walks       = true;

    // Override noise parameters. If left default, uses the NoiseModel defaults
    // which are tuned to match real LD06 measurements.
    float  noise_sigma_range_1m_mm = 15.0f;
    float  noise_dropout_prob      = 0.02f;
    float  noise_specular_prob     = 0.01f;
};

// ─── SimLidar ─────────────────────────────────────────────────────────────────

class SimLidar : public sensors::LidarBase {
public:
    // ── Construction ──────────────────────────────────────────────────────────
    //
    // port_or_scene : "sim://sidewalk", "sim://hallway", etc.
    //                 Passed through from make_lidar() — identical interface
    //                 to the real drivers.
    // config        : optional fine-tuning (scan rate, noise, seed, etc.)
    explicit SimLidar(std::string port_or_scene,
                      SimConfig   config = SimConfig{});

    // Destructor stops the sim thread gracefully.
    ~SimLidar() override;

    // Non-copyable (owns a thread + mutex + SimWorld).
    SimLidar(const SimLidar&)            = delete;
    SimLidar& operator=(const SimLidar&) = delete;

    // ── LidarBase interface — identical contract to LD06 / RPLidarA1 ──────────

    // "Opens" the simulated sensor: parses the scene ID, constructs the
    // SimWorld, applies noise config. Always returns true.
    bool open()  override;

    // Starts the background simulation thread. open() must be called first.
    bool start() override;

    // Signals the sim thread to stop and joins it.
    void stop()  override;

    // Closes the simulated sensor. Calls stop() if still running.
    void close() override;

    // Returns a copy of the most recently generated ScanFrame.
    // Thread-safe — same mutex pattern as LD06.
    sensors::ScanFrame get_latest_frame() const override;

    // Register / clear the per-frame callback.
    // Called from the sim thread — keep it short.
    void set_frame_callback(FrameCallback cb) override;

    // Status
    bool        is_open()    const override { return open_;    }
    bool        is_running() const override { return running_; }
    std::string error_message() const override;
    std::string model_name()   const override;

    // ── Extended sim API ──────────────────────────────────────────────────────

    // Direct access to the SimWorld for custom object injection at runtime.
    // Example: add a pedestrian mid-run to test dynamic scene changes.
    // NOT thread-safe — call only when the sim thread is stopped, or under
    // your own external lock.
    SimWorld& world() { return *world_; }
    const SimWorld& world() const { return *world_; }

    // Current simulation time in seconds.
    float sim_time_s() const { return world_ ? world_->sim_time_s : 0.0f; }

    // Frames generated so far.
    uint64_t frames_generated() const { return frame_counter_.load(); }

    // Which scene is loaded.
    SceneId scene_id() const { return scene_id_; }

    // Access the config (can be read at any time; write only before start()).
    const SimConfig& config() const { return config_; }

private:
    // ── Scene setup ───────────────────────────────────────────────────────────

    // Parses scene_id_ from port_ and builds the SimWorld accordingly.
    void build_world();

    // Scene-specific world builders — each populates world_->objects.
    void build_scene_sidewalk();
    void build_scene_crossing();
    void build_scene_hallway();
    void build_scene_parking_lot();
    void build_scene_cyclist_overtake();
    void build_scene_crowd();

    // ── Simulation thread ─────────────────────────────────────────────────────

    // Main body of the background thread.
    // Runs at config_.scan_hz, calls world_->step() + world_->cast_rays(),
    // packs results into a ScanFrame, and publishes it.
    void sim_loop();

    // Pack a vector of NoisedRay into a ScanFrame with correct metadata.
    sensors::ScanFrame pack_frame(const std::vector<NoisedRay>& rays,
                                  uint64_t frame_id) const;

    // Publish a completed frame: store in latest_frame_ and invoke callback.
    void publish_frame(sensors::ScanFrame frame);

    // ── State ─────────────────────────────────────────────────────────────────

    SimConfig               config_;
    SceneId                 scene_id_  = SceneId::Sidewalk;
    std::unique_ptr<SimWorld> world_;

    bool                    open_    = false;

    std::thread             sim_thread_;
    std::atomic<bool>       running_  { false };
    std::atomic<bool>       stop_flag_{ false };

    mutable std::mutex      frame_mutex_;
    sensors::ScanFrame      latest_frame_;
    std::atomic<uint64_t>   frame_counter_{ 0 };

    mutable std::mutex      cb_mutex_;
    FrameCallback           frame_callback_;

    mutable std::mutex      error_mutex_;
    std::string             error_str_;
};

} // namespace sim